-- =========================================================
-- Q1: RFM-Style Customer Analysis
-- File: 06_Advanced_Analytics.sql
-- =========================================================

USE EcommerceAnalytics;
GO

WITH CustomerMetrics AS
(
    SELECT
        c.customer_unique_id AS CustomerUniqueID,

        -- Most recent purchase date for the customer
        MAX(
            TRY_CONVERT(
                DATETIME2,
                o.order_purchase_timestamp
            )
        ) AS LastPurchaseDate,

        -- Number of distinct orders
        COUNT(DISTINCT o.order_id) AS Frequency,

        -- Total revenue generated by the customer
        SUM(oi.price) AS MonetaryValue

    FROM dbo.olist_customers_dataset AS c

    INNER JOIN dbo.olist_orders_dataset AS o
        ON c.customer_id = o.customer_id

    INNER JOIN dbo.olist_order_items_dataset AS oi
        ON o.order_id = oi.order_id

    WHERE o.order_purchase_timestamp IS NOT NULL

    GROUP BY
        c.customer_unique_id
),

DatasetEnd AS
(
    SELECT
        MAX(
            TRY_CONVERT(
                DATETIME2,
                order_purchase_timestamp
            )
        ) AS DatasetMaxPurchaseDate

    FROM dbo.olist_orders_dataset

    WHERE order_purchase_timestamp IS NOT NULL
)

SELECT
    cm.CustomerUniqueID,

    cm.LastPurchaseDate,

    -- Recency: days since the customer's last purchase
    DATEDIFF(
        DAY,
        cm.LastPurchaseDate,
        de.DatasetMaxPurchaseDate
    ) AS RecencyDays,

    -- Frequency: number of distinct orders
    cm.Frequency,

    -- Monetary: total customer revenue
    cm.MonetaryValue

FROM CustomerMetrics AS cm

CROSS JOIN DatasetEnd AS de

ORDER BY
    cm.MonetaryValue DESC;
GO

-- =========================================================
-- Q2: RFM Customer Scoring
-- =========================================================

WITH CustomerRFM AS
(
    SELECT
        c.customer_unique_id AS CustomerUniqueID,

        MAX(
            TRY_CONVERT(
                DATETIME2,
                o.order_purchase_timestamp
            )
        ) AS LastPurchaseDate,

        COUNT(DISTINCT o.order_id) AS Frequency,

        SUM(oi.price) AS MonetaryValue

    FROM dbo.olist_customers_dataset AS c

    INNER JOIN dbo.olist_orders_dataset AS o
        ON c.customer_id = o.customer_id

    INNER JOIN dbo.olist_order_items_dataset AS oi
        ON o.order_id = oi.order_id

    GROUP BY
        c.customer_unique_id
),

DatasetEnd AS
(
    SELECT
        MAX(
            TRY_CONVERT(
                DATETIME2,
                order_purchase_timestamp
            )
        ) AS DatasetMaxDate

    FROM dbo.olist_orders_dataset
),

RFMBase AS
(
    SELECT
        r.CustomerUniqueID,

        DATEDIFF(
            DAY,
            r.LastPurchaseDate,
            d.DatasetMaxDate
        ) AS RecencyDays,

        r.Frequency,

        r.MonetaryValue

    FROM CustomerRFM AS r
    CROSS JOIN DatasetEnd AS d
)

SELECT
    CustomerUniqueID,
    RecencyDays,
    Frequency,
    MonetaryValue,

    -- Lower recency = better score
    CASE
        WHEN RecencyDays <= 30 THEN 5
        WHEN RecencyDays <= 90 THEN 4
        WHEN RecencyDays <= 180 THEN 3
        WHEN RecencyDays <= 365 THEN 2
        ELSE 1
    END AS RecencyScore,

    CASE
        WHEN Frequency >= 5 THEN 5
        WHEN Frequency = 4 THEN 4
        WHEN Frequency = 3 THEN 3
        WHEN Frequency = 2 THEN 2
        ELSE 1
    END AS FrequencyScore,

    CASE
        WHEN MonetaryValue >= 1000 THEN 5
        WHEN MonetaryValue >= 500 THEN 4
        WHEN MonetaryValue >= 250 THEN 3
        WHEN MonetaryValue >= 100 THEN 2
        ELSE 1
    END AS MonetaryScore

FROM RFMBase
ORDER BY
    MonetaryValue DESC;
GO

-- =========================================================
-- Q3: Customer RFM Segmentation
-- =========================================================

WITH RFMData AS
(
    SELECT
        c.customer_unique_id AS CustomerUniqueID,

        MAX(
            TRY_CONVERT(
                DATETIME2,
                o.order_purchase_timestamp
            )
        ) AS LastPurchaseDate,

        COUNT(DISTINCT o.order_id) AS Frequency,

        SUM(oi.price) AS MonetaryValue

    FROM dbo.olist_customers_dataset AS c

    INNER JOIN dbo.olist_orders_dataset AS o
        ON c.customer_id = o.customer_id

    INNER JOIN dbo.olist_order_items_dataset AS oi
        ON o.order_id = oi.order_id

    GROUP BY
        c.customer_unique_id
),

DatasetEnd AS
(
    SELECT
        MAX(
            TRY_CONVERT(
                DATETIME2,
                order_purchase_timestamp
            )
        ) AS DatasetMaxDate

    FROM dbo.olist_orders_dataset
),

ScoredRFM AS
(
    SELECT
        r.CustomerUniqueID,

        DATEDIFF(
            DAY,
            r.LastPurchaseDate,
            d.DatasetMaxDate
        ) AS RecencyDays,

        r.Frequency,
        r.MonetaryValue

    FROM RFMData AS r
    CROSS JOIN DatasetEnd AS d
)

SELECT
    CustomerUniqueID,
    RecencyDays,
    Frequency,
    MonetaryValue,

    CASE
        WHEN RecencyDays <= 30
         AND Frequency >= 3
         AND MonetaryValue >= 500
            THEN 'Champions'

        WHEN RecencyDays <= 90
         AND Frequency >= 2
            THEN 'Loyal Customers'

        WHEN RecencyDays <= 180
         AND MonetaryValue >= 250
            THEN 'Potential Loyalists'

        WHEN RecencyDays > 365
         AND Frequency = 1
            THEN 'At Risk'

        WHEN RecencyDays > 180
            THEN 'Inactive'

        ELSE 'Regular Customers'
    END AS CustomerSegment

FROM ScoredRFM;
GO

-- =========================================================
-- Q4: Customer Revenue Concentration / Pareto Analysis
-- =========================================================

WITH CustomerRevenue AS
(
    SELECT
        c.customer_unique_id AS CustomerUniqueID,
        SUM(oi.price) AS TotalRevenue

    FROM dbo.olist_customers_dataset AS c

    INNER JOIN dbo.olist_orders_dataset AS o
        ON c.customer_id = o.customer_id

    INNER JOIN dbo.olist_order_items_dataset AS oi
        ON o.order_id = oi.order_id

    GROUP BY
        c.customer_unique_id
),

RevenueRanking AS
(
    SELECT
        CustomerUniqueID,
        TotalRevenue,

        SUM(TotalRevenue) OVER () AS GrandTotalRevenue,

        SUM(TotalRevenue) OVER (
            ORDER BY TotalRevenue DESC
            ROWS BETWEEN UNBOUNDED PRECEDING
            AND CURRENT ROW
        ) AS CumulativeRevenue

    FROM CustomerRevenue
)

SELECT
    CustomerUniqueID,
    TotalRevenue,

    CAST(
        CumulativeRevenue * 100.0
        / NULLIF(GrandTotalRevenue, 0)
        AS DECIMAL(10,2)
    ) AS CumulativeRevenuePercent,

    CASE
        WHEN CumulativeRevenue * 100.0
             / NULLIF(GrandTotalRevenue, 0) <= 20
            THEN 'Top 20% Revenue Contributors'

        WHEN CumulativeRevenue * 100.0
             / NULLIF(GrandTotalRevenue, 0) <= 50
            THEN 'Top 50% Revenue Contributors'

        ELSE 'Remaining Customers'
    END AS RevenueContributionGroup

FROM RevenueRanking
ORDER BY
    TotalRevenue DESC;
GO

-- =========================================================
-- Q5: Repeat vs One-Time Customer Revenue
-- =========================================================

WITH CustomerOrders AS
(
    SELECT
        c.customer_unique_id AS CustomerUniqueID,

        COUNT(DISTINCT o.order_id) AS TotalOrders,

        SUM(oi.price) AS TotalRevenue

    FROM dbo.olist_customers_dataset AS c

    INNER JOIN dbo.olist_orders_dataset AS o
        ON c.customer_id = o.customer_id

    INNER JOIN dbo.olist_order_items_dataset AS oi
        ON o.order_id = oi.order_id

    GROUP BY
        c.customer_unique_id
)

SELECT
    CASE
        WHEN TotalOrders > 1
            THEN 'Repeat Customer'
        ELSE 'One-Time Customer'
    END AS CustomerType,

    COUNT(*) AS TotalCustomers,

    SUM(TotalOrders) AS TotalOrders,

    SUM(TotalRevenue) AS TotalRevenue,

    CAST(
        AVG(TotalRevenue)
        AS DECIMAL(12,2)
    ) AS AverageCustomerRevenue

FROM CustomerOrders

GROUP BY
    CASE
        WHEN TotalOrders > 1
            THEN 'Repeat Customer'
        ELSE 'One-Time Customer'
    END

ORDER BY
    TotalRevenue DESC;
GO

-- =========================================================
-- Q6: Category Revenue vs Customer Satisfaction
-- =========================================================

SELECT
    COALESCE(
        t.product_category_name_english,
        p.product_category_name,
        'Unknown'
    ) AS ProductCategory,

    SUM(oi.price) AS TotalRevenue,

    COUNT(DISTINCT oi.order_id) AS TotalOrders,

    COUNT(DISTINCT r.review_id) AS TotalReviews,

    CAST(
        AVG(
            CAST(r.review_score AS DECIMAL(10,2))
        )
        AS DECIMAL(10,2)
    ) AS AverageReviewScore,

    CAST(
        SUM(oi.price) * 1.0
        / NULLIF(COUNT(DISTINCT oi.order_id), 0)
        AS DECIMAL(12,2)
    ) AS RevenuePerOrder

FROM dbo.olist_products_dataset AS p

INNER JOIN dbo.olist_order_items_dataset AS oi
    ON p.product_id = oi.product_id

LEFT JOIN dbo.olist_order_reviews_dataset AS r
    ON oi.order_id = r.order_id

LEFT JOIN dbo.product_category_name_translation AS t
    ON p.product_category_name = t.product_category_name

GROUP BY
    COALESCE(
        t.product_category_name_english,
        p.product_category_name,
        'Unknown'
    )

HAVING
    COUNT(DISTINCT r.review_id) >= 100

ORDER BY
    TotalRevenue DESC;
GO

-- =========================================================
-- Q7: Seller Revenue vs Delivery Performance
-- =========================================================

SELECT TOP 20

    s.seller_id AS SellerID,

    s.seller_city AS SellerCity,

    s.seller_state AS SellerState,

    COUNT(DISTINCT oi.order_id) AS TotalOrders,

    SUM(oi.price) AS TotalRevenue,

    COUNT(
        DISTINCT CASE
            WHEN o.order_delivered_customer_date IS NOT NULL
            THEN oi.order_id
        END
    ) AS DeliveredOrders,

    COUNT(
        DISTINCT CASE
            WHEN o.order_delivered_customer_date IS NOT NULL
             AND TRY_CONVERT(
                    DATETIME2,
                    o.order_delivered_customer_date
                 )
                 >
                 TRY_CONVERT(
                    DATETIME2,
                    o.order_estimated_delivery_date
                 )
            THEN oi.order_id
        END
    ) AS LateOrders,

    CAST(
        COUNT(
            DISTINCT CASE
                WHEN o.order_delivered_customer_date IS NOT NULL
                 AND TRY_CONVERT(
                        DATETIME2,
                        o.order_delivered_customer_date
                     )
                     >
                     TRY_CONVERT(
                        DATETIME2,
                        o.order_estimated_delivery_date
                     )
                THEN oi.order_id
            END
        ) * 100.0
        /
        NULLIF(
            COUNT(
                DISTINCT CASE
                    WHEN o.order_delivered_customer_date IS NOT NULL
                    THEN oi.order_id
                END
            ),
            0
        )
        AS DECIMAL(10,2)
    ) AS LateDeliveryRatePercent

FROM dbo.olist_sellers_dataset AS s

INNER JOIN dbo.olist_order_items_dataset AS oi
    ON s.seller_id = oi.seller_id

INNER JOIN dbo.olist_orders_dataset AS o
    ON oi.order_id = o.order_id

GROUP BY
    s.seller_id,
    s.seller_city,
    s.seller_state

HAVING
    COUNT(
        DISTINCT CASE
            WHEN o.order_delivered_customer_date IS NOT NULL
            THEN oi.order_id
        END
    ) >= 20

ORDER BY
    TotalRevenue DESC;
GO