-- =========================================================
-- Q1: Order Performance View
-- =========================================================

USE EcommerceAnalytics;
GO

CREATE OR ALTER VIEW dbo.vw_OrderPerformance
AS
SELECT
    o.order_id AS OrderID,
    o.customer_id AS CustomerID,
    o.order_status AS OrderStatus,

    TRY_CONVERT(
        DATETIME2,
        o.order_purchase_timestamp
    ) AS PurchaseDate,

    TRY_CONVERT(
        DATETIME2,
        o.order_delivered_customer_date
    ) AS DeliveredDate,

    TRY_CONVERT(
        DATETIME2,
        o.order_estimated_delivery_date
    ) AS EstimatedDeliveryDate,

    -- Total number of items in the order
    COUNT(oi.order_item_id) AS TotalItems,

    -- Total product revenue
    SUM(oi.price) AS TotalRevenue,

    -- Total freight cost
    SUM(oi.freight_value) AS TotalFreight,

    -- Delivery days
    CASE
        WHEN o.order_delivered_customer_date IS NOT NULL
        THEN DATEDIFF(
            DAY,
            TRY_CONVERT(
                DATETIME2,
                o.order_purchase_timestamp
            ),
            TRY_CONVERT(
                DATETIME2,
                o.order_delivered_customer_date
            )
        )
        ELSE NULL
    END AS DeliveryDays,

    -- Delivery classification
    CASE
        WHEN o.order_delivered_customer_date IS NULL
            THEN 'Not Delivered'

        WHEN TRY_CONVERT(
                DATETIME2,
                o.order_delivered_customer_date
             )
             <=
             TRY_CONVERT(
                DATETIME2,
                o.order_estimated_delivery_date
             )
            THEN 'Delivered On Time'

        ELSE 'Delivered Late'
    END AS DeliveryStatus

FROM dbo.olist_orders_dataset AS o

LEFT JOIN dbo.olist_order_items_dataset AS oi
    ON o.order_id = oi.order_id

GROUP BY
    o.order_id,
    o.customer_id,
    o.order_status,
    o.order_purchase_timestamp,
    o.order_delivered_customer_date,
    o.order_estimated_delivery_date;
GO

-- VERIFY THE RESULT
SELECT TOP 10 *
FROM dbo.vw_OrderPerformance;
GO

-- =========================================================
-- Q2: Customer 360 View
-- =========================================================

CREATE OR ALTER VIEW dbo.vw_Customer360
AS

SELECT
    c.customer_unique_id AS CustomerUniqueID,

    -- Customer location
    MAX(c.customer_city) AS CustomerCity,
    MAX(c.customer_state) AS CustomerState,

    -- Number of unique orders
    COUNT(DISTINCT o.order_id) AS TotalOrders,

    -- Number of products/items purchased
    COUNT(oi.order_item_id) AS TotalItems,

    -- Total revenue generated by the customer
    SUM(oi.price) AS TotalRevenue,

    -- Average order value
    CAST(
        SUM(oi.price) * 1.0
        / NULLIF(COUNT(DISTINCT o.order_id), 0)
        AS DECIMAL(12,2)
    ) AS AverageOrderValue

FROM dbo.olist_customers_dataset AS c

INNER JOIN dbo.olist_orders_dataset AS o
    ON c.customer_id = o.customer_id

INNER JOIN dbo.olist_order_items_dataset AS oi
    ON o.order_id = oi.order_id

GROUP BY
    c.customer_unique_id;
GO


-- =========================================================
-- Test the Customer 360 View
-- =========================================================

SELECT TOP 10 *
FROM dbo.vw_Customer360
ORDER BY TotalRevenue DESC;
GO

-- =========================================================
-- Q3: Product Performance View
-- =========================================================

USE EcommerceAnalytics;
GO

CREATE OR ALTER VIEW dbo.vw_ProductPerformance
AS

SELECT
    p.product_id AS ProductID,

    COALESCE(
        t.product_category_name_english,
        p.product_category_name,
        'Unknown'
    ) AS ProductCategory,

    -- Number of items sold
    COUNT(*) AS TotalItemsSold,

    -- Number of unique orders containing the product
    COUNT(DISTINCT oi.order_id) AS TotalOrders,

    -- Total revenue generated
    SUM(oi.price) AS TotalRevenue,

    -- Average selling price
    CAST(
        AVG(oi.price)
        AS DECIMAL(12,2)
    ) AS AverageSellingPrice,

    -- Total freight value
    SUM(oi.freight_value) AS TotalFreight

FROM dbo.olist_products_dataset AS p

INNER JOIN dbo.olist_order_items_dataset AS oi
    ON p.product_id = oi.product_id

LEFT JOIN dbo.product_category_name_translation AS t
    ON p.product_category_name = t.product_category_name

GROUP BY
    p.product_id,
    COALESCE(
        t.product_category_name_english,
        p.product_category_name,
        'Unknown'
    );
GO


-- =========================================================
-- Test the Product Performance View
-- =========================================================

SELECT TOP 10 *
FROM dbo.vw_ProductPerformance
ORDER BY TotalRevenue DESC;
GO

-- =========================================================
-- Q4: Seller Performance View
-- =========================================================

CREATE OR ALTER VIEW dbo.vw_SellerPerformance
AS

SELECT
    s.seller_id AS SellerID,
    s.seller_city AS SellerCity,
    s.seller_state AS SellerState,

    -- Number of unique orders handled
    COUNT(DISTINCT oi.order_id) AS TotalOrders,

    -- Total items sold
    COUNT(*) AS TotalItemsSold,

    -- Total revenue
    SUM(oi.price) AS TotalRevenue,

    -- Average selling price
    CAST(
        AVG(oi.price)
        AS DECIMAL(12,2)
    ) AS AverageItemPrice,

    -- Total freight value
    SUM(oi.freight_value) AS TotalFreight

FROM dbo.olist_sellers_dataset AS s

INNER JOIN dbo.olist_order_items_dataset AS oi
    ON s.seller_id = oi.seller_id

GROUP BY
    s.seller_id,
    s.seller_city,
    s.seller_state;
GO


-- =========================================================
-- Test Seller Performance View
-- =========================================================

SELECT TOP 10 *
FROM dbo.vw_SellerPerformance
ORDER BY TotalRevenue DESC;
GO

-- =========================================================
-- Q5: Payment Performance View
-- ========================================================

CREATE OR ALTER VIEW dbo.vw_PaymentPerformance
AS

SELECT
    payment_type AS PaymentType,

    COUNT(DISTINCT order_id) AS TotalOrders,

    SUM(payment_value) AS TotalPaymentValue,

    CAST(
        AVG(payment_value)
        AS DECIMAL(12,2)
    ) AS AveragePaymentValue,

    SUM(payment_installments) AS TotalInstallments

FROM dbo.olist_order_payments_dataset

GROUP BY
    payment_type;
GO


-- Test the view

SELECT *
FROM dbo.vw_PaymentPerformance
ORDER BY TotalPaymentValue DESC;
GO

-- =========================================================
-- Q6: Product Category Review Performance View
-- =========================================================

CREATE OR ALTER VIEW dbo.vw_CategoryReviewPerformance
AS

SELECT
    COALESCE(
        t.product_category_name_english,
        p.product_category_name,
        'Unknown'
    ) AS ProductCategory,

    COUNT(DISTINCT r.review_id) AS TotalReviews,

    CAST(
        AVG(
            CAST(r.review_score AS DECIMAL(10,2))
        )
        AS DECIMAL(10,2)
    ) AS AverageReviewScore,

    SUM(
        CASE
            WHEN r.review_score IN (4,5)
            THEN 1
            ELSE 0
        END
    ) AS PositiveReviews,

    SUM(
        CASE
            WHEN r.review_score = 3
            THEN 1
            ELSE 0
        END
    ) AS NeutralReviews,

    SUM(
        CASE
            WHEN r.review_score IN (1,2)
            THEN 1
            ELSE 0
        END
    ) AS NegativeReviews

FROM dbo.olist_products_dataset AS p

INNER JOIN dbo.olist_order_items_dataset AS oi
    ON p.product_id = oi.product_id

INNER JOIN dbo.olist_order_reviews_dataset AS r
    ON oi.order_id = r.order_id

LEFT JOIN dbo.product_category_name_translation AS t
    ON p.product_category_name = t.product_category_name

GROUP BY
    COALESCE(
        t.product_category_name_english,
        p.product_category_name,
        'Unknown'
    );
GO


-- Test the view

SELECT TOP 10 *
FROM dbo.vw_CategoryReviewPerformance
ORDER BY AverageReviewScore DESC;
GO

-- =========================================================
-- Q7: Executive KPI View
-- =========================================================

CREATE OR ALTER VIEW dbo.vw_ExecutiveKPIs
AS

SELECT

    -- Total unique customers
    (
        SELECT COUNT(DISTINCT customer_unique_id)
        FROM dbo.olist_customers_dataset
    ) AS TotalCustomers,

    -- Total orders
    (
        SELECT COUNT(DISTINCT order_id)
        FROM dbo.olist_orders_dataset
    ) AS TotalOrders,

    -- Total products
    (
        SELECT COUNT(DISTINCT product_id)
        FROM dbo.olist_products_dataset
    ) AS TotalProducts,

    -- Total sellers
    (
        SELECT COUNT(DISTINCT seller_id)
        FROM dbo.olist_sellers_dataset
    ) AS TotalSellers,

    -- Total revenue
    (
        SELECT SUM(price)
        FROM dbo.olist_order_items_dataset
    ) AS TotalRevenue,

    -- Average order value
    (
        SELECT
            CAST(
                SUM(price) * 1.0
                / NULLIF(COUNT(DISTINCT order_id),0)
                AS DECIMAL(12,2)
            )
        FROM dbo.olist_order_items_dataset
    ) AS AverageOrderValue,

    -- Average review score
    (
        SELECT
            CAST(
                AVG(
                    CAST(review_score AS DECIMAL(10,2))
                )
                AS DECIMAL(10,2)
            )
        FROM dbo.olist_order_reviews_dataset
    ) AS AverageReviewScore,

    -- Total freight
    (
        SELECT SUM(freight_value)
        FROM dbo.olist_order_items_dataset
    ) AS TotalFreight,

    -- Delivered orders
    (
        SELECT COUNT(*)
        FROM dbo.olist_orders_dataset
        WHERE order_delivered_customer_date IS NOT NULL
    ) AS DeliveredOrders,

    -- Late delivered orders
    (
        SELECT COUNT(*)
        FROM dbo.olist_orders_dataset
        WHERE order_delivered_customer_date IS NOT NULL
          AND TRY_CONVERT(
                DATETIME2,
                order_delivered_customer_date
              )
              >
              TRY_CONVERT(
                DATETIME2,
                order_estimated_delivery_date
              )
    ) AS LateOrders;
GO


-- Test the Executive KPI View

SELECT *
FROM dbo.vw_ExecutiveKPIs;
GO